/*

Animal Crossing: New Horizons turnip price tracking database

*/

CREATE DATABASE turnips;

USE turnips;

CREATE TABLE users
/* Site users */
(
	user_id INT AUTO_INCREMENT,
    user_name VARCHAR(255),
    PRIMARY KEY (user_id)
);

CREATE TABLE date_helper_week
/* Date data to facilitate week grouping */
(
	week_id INT,
    start_date DATETIME,
    end_date DATETIME,
    last_week_id INT,
    PRIMARY KEY (week_id),
    INDEX (start_date),
    INDEX (end_date),
    INDEX (last_week_id)
);

CREATE TABLE date_helper_day
/* Date data to facilitate daily grouping */
(
	dat DATETIME,
    yesterdat DATETIME,
    last_week DATETIME,
    day_of_week INT,
    week_id INT,
    PRIMARY KEY (dat),
    FOREIGN KEY (week_id)
		REFERENCES date_helper_week (week_id),
	INDEX (day_of_week)
);

CREATE TABLE turnip_prices
/* Organic sell price data sourced from users */
(
	dat DATETIME,
    user_id INT,
    price INT,
    PRIMARY KEY (dat, user_id),
    FOREIGN KEY (user_id)
		REFERENCES users (user_id)
        ON DELETE CASCADE
);

CREATE TABLE purchase_prices
/* Organic purchase price data sourced from users */
(
	user_id INT,
    week_id INT,
    purchase_price INT,
    PRIMARY KEY (user_id, week_id),
    FOREIGN KEY (user_id)
		REFERENCES users (user_id)
        ON DELETE CASCADE,
    FOREIGN KEY (week_id)
		REFERENCES date_helper_week (week_id)   
);

CREATE TABLE generated_turnip_prices
/* Prices generated by and scraped from http://turnip-price.now.sh */
(
    `Purchase` INT,
    `Mon-AM` INT,
    `Mon-PM` INT,
    `Tues-AM` INT,
    `Tues-PM` INT,
    `Wed-AM` INT,
    `Wed-PM` INT,
    `Thurs-AM` INT,
    `Thurs-PM` INT,
    `Fri-AM` INT,
    `Fri-PM` INT,
    `Sat-AM` INT,
    `Sat-PM` INT
);
